FROM node:17-alpine3.14
WORKDIR /frontend
COPY package.json package-lock.json ./
RUN npm install && \
    npm install react-scripts@5.0.0 -g && \
    npm install javascript-time-ago && \
    npm install react-time-ago && \
    npm install react-paginate

COPY . /
RUN chmod 777 node_modules -R
EXPOSE 3000
CMD npm start
