#To (re)build services using development environment use command below:
# docker-compose build

#To start containers using development environment use command:
# docker-compose up

# !NOTE: sudo prefix may be needed for docker commands to function properly

version: "3"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwerty
    volumes:
      - postgres_data:/var/lib/postgresql/data
  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile.dev
    command: >
      sh -c "cd backend &&
             python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py test &&
             python manage.py runserver 0.0.0.0:5432"
    volumes:
      - .:/backend
    ports:
      - "5432:5432"
    depends_on:
      - db
  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile.dev
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - /frontend/node_modules
      - ./frontend:/frontend/
    ports:
      - "3000:3000"
    stdin_open: true
    depends_on:
      - backend
volumes:
  postgres_data:
