version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwerty
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  backend: 
    build:
      context: ./backend/
      dockerfile: Dockerfile
    #command: sh -c "cd ./backend && gunicorn project.wsgi --bind 0.0.0.0:5432"
    command: sh -c "python manage.py makemigrations &&
                    python manage.py migrate &&
                    python manage.py collectstatic --noinput &&
                    gunicorn project.wsgi:application --bind 0.0.0.0:5432"
    volumes:
      - .:/microservice:rw
      - static_volume:/home/app/microservice/static
    expose:
      - 5432
    depends_on:
      - db
  frontend:
    command : 
      npm start
      npm run build
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    volumes:
      - react_build:/frontend/build
    ports:
      - "3000:3000"
    stdin_open: true
    depends_on:
      - backend
  nginx:
    build: ./nginx
    ports:
      - 5432:80
    volumes:
      - static_volume:/home/app/microservice/static
    depends_on:
      - backend
    
volumes:
  postgres_data:
  static_volume:
  react_build:

