version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwerty
    volumes: 
      - .:/code/db
  backend: 
    build:
      context: ./backend/
      dockerfile: Dockerfile
    command: python ./backend/manage.py runserver 0.0.0.0:5432
    volumes: 
      - .:/code/backend
    ports:
      - "5432:5432"
    depends_on:
      - db
  frontend:
    command : npm start
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    stdin_open: true
    depends_on:
      - backend