# Generated by Django 4.0 on 2022-03-06 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CopyCasket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('author', models.CharField(max_length=30)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('jk', 'Joke'), ('cd', 'Code'), ('in', 'Information'), ('as', 'ASCII'), ('us', 'Unspecified')], default='us', max_length=2)),
                ('content', models.TextField(blank=True)),
            ],
        ),
    ]
