# Generated by Django 4.0.3 on 2022-03-30 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("copycasket", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="last_name",
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
