# Generated by Django 4.0.3 on 2022-03-17 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copycasket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copycasket',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
