# Generated by Django 4.0.3 on 2022-03-30 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("copycasket", "0002_customuser_last_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(max_length=254, unique=True, verbose_name="email"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="first_name",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="last_name",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="username",
            field=models.CharField(max_length=30, unique=True, verbose_name="username"),
        ),
    ]
