# Generated by Django 4.0.3 on 2022-04-27 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copycasket', '0005_copycasket_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='copycasket',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
