# Generated by Django 4.0.3 on 2022-05-09 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('copycasket', '0007_alter_copycasket_image_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='copy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='copycasket.copycasket'),
        ),
    ]
