# Generated by Django 4.0.3 on 2022-05-19 06:56

import copycasket.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("copycasket", "0011_alter_copycasket_likes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="copy",
            field=models.ForeignKey(
                default=copycasket.models.CopyCasket.get_default_pk,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="copyReport",
                to="copycasket.copycasket",
            ),
        ),
    ]
