# Generated by Django 4.0.3 on 2022-05-25 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('copycasket', '0011_alter_copycasket_likes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='copycasket',
            options={'ordering': ['-creation_date']},
        ),
    ]
