# Generated by Django 4.0.3 on 2022-05-25 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('copycasket', '0012_alter_report_copy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='copycasket',
            options={'ordering': ['-creation_date']},
        ),
    ]
