# Generated by Django 4.0.3 on 2022-05-26 00:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('copycasket', '0013_alter_copycasket_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copycasket',
            name='creator',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
    ]
