# Generated by Django 4.0.3 on 2022-05-26 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("copycasket", "0014_alter_copycasket_creator"),
    ]

    operations = [
        migrations.AddField(
            model_name="copycasket",
            name="expiration_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
